#include <iostream>
#include <memory>
#include <verilated.h>
#include <iomanip>
#include <vector>
#include <cmath>
#include "Vhft_top.h" // Automatically generated by Verilator build context
#include "latency_tracker.h"

// Global Time Context Variable  
vluint64_t main_time = 0;

struct FPGALatencyMeasurement {
    uint64_t msg_arrival_cycle;
    uint64_t order_send_cycle;
    uint64_t latency_cycles;
    std::string msg_description;
};

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    
    // Instantiate hardware top module
    auto top = std::make_unique<Vhft_top>();
    LatencyTracker latency_tracker;
    std::vector<FPGALatencyMeasurement> measurements;

    // Apply System Hardware Reset Sequence
    top->clk = 0;
    top->reset = 1;
    top->itch_msg_valid = 0;
    top->ouch_tready = 1; // Downstream network link ready
    
    for (int i = 0; i < 5; ++i) {
        top->clk = !top->clk; top->eval();
        top->clk = !top->clk; top->eval();
    }
    top->reset = 0;
    std::cout << "\n" << std::string(60, '=') << std::endl;
    std::cout << "  FPGA Hardware Latency Benchmark (Verilated)" << std::endl;
    std::cout << std::string(60, '=') << "\n" << std::endl;
    std::cout << "[SIM] Hardware Engine Reset Complete. Starting Tick Loop." << std::endl;

    // --- LATENCY MEASUREMENT TEST SEQUENCE ---
    std::cout << "\n[*] Injecting test messages and measuring latency...\n" << std::endl;

    struct TestMessage {
        uint8_t type;
        uint16_t locate;
        uint8_t side;
        uint32_t price;
        uint32_t shares;
        uint64_t order_id;
        std::string desc;
    };

    std::vector<TestMessage> test_messages = {
        {'A', 1337, 1, 1500000, 2000, 99991, "ADD Buy 2000 @ $150.00"},
        {'A', 1337, 0, 1500100, 1500, 99992, "ADD Sell 1500 @ $150.01"},
        {'A', 1337, 1, 1500050, 3000, 99993, "ADD Buy 3000 @ $150.005"},
        {'E', 1337, 1, 1500000, 500,  99991, "EXEC 500 from buy"},
        {'X', 1337, 0, 1500100, 300,  99992, "CANCEL 300 from sell"},
    };

    // Cycle counter for measurements
    uint64_t cycle_counter = 0;
    
    for (const auto& msg : test_messages) {
        uint64_t msg_arrival_cycle = cycle_counter;
        
        // Inject message on clock rising edge
        top->clk = 0;
        top->eval();
        cycle_counter++;
        
        top->itch_msg_valid   = 1;
        top->itch_msg_type    = msg.type;
        top->itch_msg_locate  = msg.locate;
        top->itch_msg_side    = msg.side;
        top->itch_msg_shares  = msg.shares;
        top->itch_msg_price   = msg.price;
        top->itch_msg_order_id = msg.order_id;
        
        top->clk = 1;
        top->eval();
        cycle_counter++;
        
        // Release message
        top->itch_msg_valid = 0;
        
        // Poll for order transmission (up to 100 cycles)
        uint64_t order_send_cycle = 0;
        bool order_sent = false;
        
        for (int poll = 0; poll < 100; ++poll) {
            top->clk = 0;
            top->eval();
            cycle_counter++;
            
            top->clk = 1;
            top->eval();
            cycle_counter++;
            
            // Check if order was generated on this cycle
            if (top->ouch_tvalid) {
                order_send_cycle = cycle_counter;
                order_sent = true;
                std::cout << "  [✓] Order transmitted" << std::endl;
                break;
            }
        }
        
        // Calculate latency
        uint64_t latency_cycles = order_send_cycle - msg_arrival_cycle;
        double latency_ns = (double)latency_cycles * 1.0;  // 1 GHz = 1 ns per cycle
        
        FPGALatencyMeasurement meas;
        meas.msg_arrival_cycle = msg_arrival_cycle;
        meas.order_send_cycle = order_send_cycle;
        meas.latency_cycles = latency_cycles;
        meas.msg_description = msg.desc;
        measurements.push_back(meas);
        
        latency_tracker.record_latency_ns(latency_ns);
        
        std::cout << "[Msg] " << std::setw(30) << std::left << msg.desc 
                 << "| Cycles: " << std::setw(3) << latency_cycles 
                 << "| Latency: " << std::fixed << std::setprecision(1) 
                 << latency_ns << " ns" << std::endl;
        
        // Add spacing between messages
        for (int spacer = 0; spacer < 10; ++spacer) {
            top->clk = 0;
            top->eval();
            cycle_counter++;
            top->clk = 1;
            top->eval();
            cycle_counter++;
        }
    }
    
    // Print benchmark results
    std::cout << "\n" << std::string(60, '=') << std::endl;
    std::cout << "                  LATENCY RESULTS" << std::endl;
    std::cout << std::string(60, '=') << "\n" << std::endl;
    
    latency_tracker.print_stats("FPGA Hardware (Verilated @ 1GHz)");
    
    auto stats = latency_tracker.compute_stats();
    std::cout << "Total Cycles Simulated: " << cycle_counter << std::endl;
    std::cout << "\nComparison with CPU:" << std::endl;
    std::cout << "  CPU Mean Latency (real data):  20.0 ns" << std::endl;
    std::cout << "  FPGA Mean Latency (hardware):  " << std::fixed << std::setprecision(1) 
              << stats.mean_ns << " ns" << std::endl;
    std::cout << std::fixed << std::setprecision(2);
    std::cout << "  Speedup Factor: " << (20.0 / stats.mean_ns) << "x\n" << std::endl;
    
    std::cout << std::string(60, '=') << std::endl;
    return 0;
}
